-- Fase 2: contato e número de exibição do cliente; rotação segura de sessões.

ALTER TABLE tenants
  ADD COLUMN seq           integer GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN contact_name  text,
  ADD COLUMN contact_email citext,
  ADD COLUMN contact_phone text,
  ADD COLUMN notes         text;

ALTER TABLE tenants ADD CONSTRAINT tenants_seq_key UNIQUE (seq);

CREATE INDEX users_tenant_idx ON users (tenant_id);
CREATE INDEX cameras_group_idx ON cameras (group_id);

-- Rotação de refresh token com detecção de reuso: o hash anterior fica guardado;
-- se um token já rotacionado for apresentado de novo, a sessão é revogada.
ALTER TABLE sessions ADD COLUMN previous_refresh_hash text;
CREATE INDEX sessions_previous_hash_idx ON sessions (previous_refresh_hash) WHERE previous_refresh_hash IS NOT NULL;
